table household
	lineageTag: 694178a9-4f72-4f20-a3df-0848bcc1892f

	column household_id
		dataType: string
		lineageTag: 09d8ab10-8573-4c4f-9c50-e3201cf5e70e
		summarizeBy: none
		sourceColumn: household_id

		annotation SummarizationSetBy = Automatic

	column household_size
		dataType: int64
		formatString: 0
		lineageTag: 6b3de086-8631-4ce7-bc23-ccff0d21b249
		summarizeBy: none
		sourceColumn: household_size

		annotation SummarizationSetBy = Automatic

	column baseline_fuel_kg_person_week
		dataType: double
		lineageTag: 2d34442c-067b-4356-8aec-5de19b7b4483
		summarizeBy: none
		sourceColumn: baseline_fuel_kg_person_week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column household_group = SWITCH(TRUE(), household[household_size]<= 3, "small size", household[household_size]<=5, "moderate size", "large size")
		lineageTag: 82e72783-445f-4505-9b03-09c51943cf10
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition household = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Kwame - PC\Desktop\Blossom\week_15\PowerBI\delagua_stove_data.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"household_id", type text}, {"district", type text}, {"zipcode", Int64.Type}, {"latitude", type number}, {"longitude", type number}, {"distribution_date", type date}, {"household_size", Int64.Type}, {"baseline_fuel_kg_person_week", type number}, {"distance_to_market_km", type number}, {"elevation_m", Int64.Type}, {"usage_month_1", type number}, {"usage_month_2", type number}, {"usage_month_3", type number}, {"usage_month_4", type number}, {"usage_month_5", type number}, {"usage_month_6", type number}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"household_id", "district", "zipcode", "latitude", "longitude", "distribution_date", "household_size", "baseline_fuel_kg_person_week", "distance_to_market_km", "elevation_m"}, "Attribute", "Value"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Unpivoted Other Columns", "Attribute", Splitter.SplitTextByEachDelimiter({"_"}, QuoteStyle.Csv, true), {"Attribute.1", "Attribute.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Attribute.1", type text}, {"Attribute.2", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type1",{"household_id", "household_size", "baseline_fuel_kg_person_week"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"household_id"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

